Something evidently went wrong - probably in whatever view.py file you're trying to access.
